language: ruby

rvm:
  - 2.1.7

sudo: required
dist: trusty

env:
  - machine_user="travis"
  - machine_pass="travis"

script:
  - bundle exec rake
  - bundle exec kitchen verify ubuntu

branches:
  only:
  - master
